### ISSUE TITLE
Curated Dataset for Training

### ISSUE THREAD

**Issue by shivangi-aneja** [wasidennis/DeepHarmonization#7]
Is it possible for you to share the complete dataset (including ground truth) you used for training the model (apart from test images you shared)?

**Comment by wasidennis** [comment]
Hi, thanks for your interest. Unfortunately, I cannot provide the code/dataset due to the IP issue (done at Adobe). If you would like to generate it on your own, you would need a color transfer function and the dataset with object mask (e.g., MSCOCO) following the procedure as described in the paper.
